### ISSUE TITLE
Missing level 4 boundary segments because of filter on type

### ISSUE THREAD

**Issue by yetzt** [geofabrik/shortbread-tilemaker#12]
The `if way:Holds("type") then return` filter in [process.lua](https://github.com/geofabrik/shortbread-tilemaker/blob/main/process.lua#L562-L564) prevents certain segments of admin_level 4 boundaries to be included, since some segments contain a `type` property: [Example](https://www.openstreetmap.org/way/52289117#map=14/53.2618/11.8605) [Overpass Query](https://overpass-turbo.eu/s/1rTb)

I don't know if this is a tagging problem since the missing segments i spotted are all within the Brandenbug/Mecklenburg-Vorpommern border, but the data has not been changed in a long time. I guess the filter on `type` is a shortcut to not to process the relations on higher level boundaries?

**Comment by Nakaner** [comment]
The current implementation returns all boundary ways which are a member of a boundary relation. Their admin_level attribute indicates the most important relation they belong to. For example, the boundary line between Baden-Württemberg and Grand Est is returned as AL 2 because it is the boundary between Germany and France as well.

Administrative boundary relations must have a `type` tag, ways should not have this tag. Way members of boundary relations are not required to have `boundary=administrative`. I used the `type` tag to distinguish ways from relations.

**Comment by yetzt** [comment]
Thanks for the clarification. [I've removed the `type` property from the affected ways](https://www.openstreetmap.org/changeset/133178082#map=11/53.3099/12.0720) which should resolve it for the future.
